// <auto-generated />
namespace PMTool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class TaskuniqueIDmodified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskuniqueIDmodified));
        
        string IMigrationMetadata.Id
        {
            get { return "201403240920209_Task unique ID modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
