// <auto-generated />
namespace PMTool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class updateemailscheduler180401 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateemailscheduler180401));
        
        string IMigrationMetadata.Id
        {
            get { return "201404180427449_updateemailscheduler180401"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
