// <auto-generated />
namespace PMTool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class taskModfied3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(taskModfied3));
        
        string IMigrationMetadata.Id
        {
            get { return "201402120850306_taskModfied3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
